// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2B1TFWWEQhYmCw2aVU8NbH1KoOUKuYf0',
    appId: '1:304110364867:web:bf07095c6b14ca43181a76',
    messagingSenderId: '304110364867',
    projectId: 'proyecto-apparq2',
    authDomain: 'proyecto-apparq2.firebaseapp.com',
    storageBucket: 'proyecto-apparq2.appspot.com',
    measurementId: 'G-21V1N2WY4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsb1-abeWQpMMbQjKn8XUJPM46II0nSS8',
    appId: '1:304110364867:android:6673eaa6642d3a81181a76',
    messagingSenderId: '304110364867',
    projectId: 'proyecto-apparq2',
    storageBucket: 'proyecto-apparq2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZv5dBfqR3SuRKyZUaabSPaLEK6CGCpc',
    appId: '1:304110364867:ios:f8d82490afbfc80f181a76',
    messagingSenderId: '304110364867',
    projectId: 'proyecto-apparq2',
    storageBucket: 'proyecto-apparq2.appspot.com',
    iosClientId: '304110364867-q6n3m7fl0knfntcml5h3c6ealtmg36ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoApp',
  );
}
